### ISSUE TITLE
Create ACS Profile Fact, Dimension Tables

### ISSUE THREAD

**Issue by dflyte** [SANDAG/DataSurfer#10]
Create fact tables for ACS housing value, contract rent, employment status, housing units (units according to Census structure type), and travel time to work. Also, create dimension tables for rent group, housing value group, travel time group, and Census structure type.

**Comment by GregorSchroeder** [comment]
was open issue, now closed prior to archive

**Comment by GregorSchroeder** [comment]
was open issue, now closed prior to archive
